[build]
command = "git submodule update --init && npm run build"
publish = "build"


[context.production]
command = "git submodule update --init && npm run build && cd service-worker && npm install && npm run build"
publish = "service-worker/dist-prod"
